/**
 * GrahaAPI types — generated by hand FROM REAL LIVE RESPONSES
 * (https://api.grahaapi.com, verified 2026-07-19 against /openapi.json and
 * live POSTs to all five wired endpoints). Do not "guess" fields here:
 * every field below was observed in an actual response or the OpenAPI spec.
 */

/* ── Requests (from /openapi.json component schemas) ────────────────────── */

export interface BirthRequest {
  dob: string;          // YYYY-MM-DD
  tob?: string;         // HH:MM — omit for sunrise chart
  lat: number;
  lon: number;
  tz: number;           // IST = 5.5
  name?: string;
  gender?: "male" | "female";
}

/** /v1/milan/ashtakoot — the live schema really is person1/person2. */
export interface MilanRequest {
  person1: BirthRequest;
  person2: BirthRequest;
}

export interface TarotRequest {
  question?: string;
  spread?: "single" | "three_card" | "celtic_cross" | "yes_no" | "past_present_future";
  deck?: "rider_waite" | "thoth" | "osho_zen" | "marseille";
  birth_chart?: BirthRequest;
  seed?: number;
}

/** /v1/rashifal/daily — POST only; takes NO rashi (returns all 12). */
export interface RashifalRequest {
  date?: string;        // YYYY-MM-DD, default today
  tz?: number;
}

export interface TransitBirthRequest {
  birth: BirthRequest;
  transit_date: string; // YYYY-MM-DD
  transit_time?: string;
}

/* ── Kundli (/v1/kundli/full) ───────────────────────────────────────────── */

export interface Nakshatra {
  index: number;
  name: string;
  name_hi: string;
  lord: string;
  pada: number;
  progress: number;
}

export interface Planet {
  longitude: number;
  latitude: number;
  distance: number;
  speed: number;
  retrograde: boolean;
  sign_index: number;
  sign: string;
  sign_hi: string;
  degrees: number;
  dms: string;
  house: number;
  dignity: string;
  interpretation_sign?: string;
  interpretation_house?: string;
  nakshatra?: Nakshatra;
  navamsa?: { sign_index: number; sign: string; sign_hi: string; navamsa_num: number };
  is_exalted?: boolean;
  is_debilitated?: boolean;
  is_mool_trikona?: boolean;
  is_own_sign?: boolean;
  is_combust?: boolean;
  is_vargottama?: boolean;
  avastha?: string;
}

export interface Yoga {
  name: string;
  planets: string[];
  strength: string;
  description: string;
}

/** One vimshottari level: { lord, start, end } — NOT a flat string. */
export interface DashaPeriod {
  lord: string;
  start: string;
  end: string;
}

export interface CurrentDasha {
  mahadasha: DashaPeriod;
  antardasha?: DashaPeriod;
  pratyantar?: DashaPeriod;
  sookshma?: DashaPeriod;
  prana?: DashaPeriod;
}

/** /v1/dasha/mahadasha — full 9-period Vimshottari sequence (~120 years). */
export interface MahadashaListResult {
  dasha: {
    moon_nakshatra: string;
    moon_nakshatra_hi: string;
    nakshatra_lord: string;
    nakshatra_progress: number;
    current: CurrentDasha;
    mahadasha: Array<{ lord: string; start: string; end: string; years?: number }>;
  };
}

export interface KundliFullResult {
  ascendant: {
    tropical: number;
    sidereal: number;
    ayanamsa: number;
    sign_index: number;
    sign: string;
    sign_hi: string;
    degrees: number;
    dms: string;
  };
  /** Array, not a Record — [{house, sign_index, sign, sign_hi, start, end}] */
  houses: Array<{
    house: number;
    sign_index: number;
    sign: string;
    sign_hi: string;
    start: number;
    end: number;
  }>;
  planets: Record<string, Planet>;
  moon_nakshatra: Nakshatra;
  yogas: Yoga[];
  current_dasha: CurrentDasha;
  lagna_personality: string;
}

/* ── Milan (/v1/milan/ashtakoot) ────────────────────────────────────────── */

export interface AshtakootResult {
  varna: { score: number; max: number; boy_varna: string; girl_varna: string };
  vashya: { score: number; max: number; boy_group: string; girl_group: string };
  tara: { score: number; max: number; tara_from_boy?: number; tara_from_girl?: number; auspicious?: boolean };
  yoni: { score: number; max: number; boy_yoni: string; girl_yoni: string };
  graha_maitri: {
    score: number; max: number;
    boy_moon_sign_lord?: string; girl_moon_sign_lord?: string;
  };
  gana: { score: number; max: number; boy_gana: string; girl_gana: string };
  bhakoot: { score: number; max: number; difference?: number; note?: string };
  nadi: { score: number; max: number; boy_nadi?: string; girl_nadi?: string; nadi_dosha: boolean };
  total: number;        // can be fractional (e.g. 20.0, tara gives halves)
  max: number;          // 36
  percentage: number;
  verdict: string;      // bilingual, e.g. "सामान्य / Average"
  person1?: {
    nakshatra: string; nakshatra_lord: string;
    moon_sign: string; moon_sign_hi: string; moon_dms?: string;
  };
  person2?: {
    nakshatra: string; nakshatra_lord: string;
    moon_sign: string; moon_sign_hi: string; moon_dms?: string;
  };
}

/* ── Rashifal (/v1/rashifal/daily) — ALL 12 rashis in one response ──────── */

export interface RashiPredictionTexts {
  overall: string;
  career: string;
  health: string;
  finance: string;
  love: string;
  spirit: string;
  stars_label: string;
}

export interface RashiPrediction {
  rashi_index: number;
  rashi_en: string;
  rashi_hi: string;
  rashi_lord: string;
  symbol: string;
  overall_stars: number;                 // 1–5
  domain_stars: { career: number; health: number; finance: number; love: number; spirit: number };
  lucky: { number: number; colors: string[]; day: string; mantra: string };
  auspicious_hours: string[];            // e.g. "06:00-07:30"
  predictions_hi: RashiPredictionTexts;
  predictions_en: RashiPredictionTexts;
}

export interface RashifalDailyResult {
  date: string;
  rashifal: RashiPrediction[];           // always 12 entries
  transit_summary: Record<
    string,
    { sign: string; sign_hi: string; sign_index: number; longitude: number; retrograde: boolean }
  >;
}

/* ── Tarot (/v1/tarot/draw) ─────────────────────────────────────────────── */

export interface TarotCard {
  id: number;
  name: string;
  name_hi: string;
  suit: string;
  value: string;
  element: string;                       // e.g. "Air / वायु"
  domain: string;
  keywords: string[];
  position: string;                      // "card_1"…
  reversed: boolean;
  interpretation_hi: string;
  interpretation_en: string;
}

export interface TarotResult {
  reading: { reading_id: string; timestamp: string; seed_used: number | null; seed_str: string };
  spread: string;
  deck: string;
  cards_drawn: number;
  cards: TarotCard[];
  question: string | null;
  note: string;
}

/* ── Panchang (/v1/panchang/full, /v1/panchang/rahu-kaal, /v1/panchang/muhurta) ── */

export interface PanchangFullResult {
  date: string;
  tithi: { number: number; paksha: string; name: string; paksha_num: number; completion: number; end_time: string };
  nakshatra: { index: number; name: string; name_hi: string; lord: string; pada: number; progress: number; end_time: string };
  yoga: { index: number; name: string; progress: number; end_time: string };
  karana: { number: number; name: string; completion: number; end_time: string };
  vara: { index: number; name: string; lord: string; note?: string };
  moon_phase: string;
  sun_rise: string;
  sun_set: string;
}

export interface KaalWindow {
  start: string;
  end: string;
  note: string;
}

export interface RahuKaalResult {
  vara: string;
  rahu_kaal: KaalWindow;
  gulika_kaal: KaalWindow;
  yamaganda: KaalWindow;
  sunrise: string;
  sunset: string;
}

export interface MuhurtaSlot {
  slot: number;
  name: string;
  type: string;          // day | night
  start: string;
  end: string;
  quality: string;       // Auspicious | Inauspicious | ...
  abhijit?: boolean;
}

export interface MuhurtaResult {
  muhurta: MuhurtaSlot[];
}

export interface FestivalItem {
  date: string;          // YYYY-MM-DD
  name: string;          // "Shukla Ekadashi (एकादशी)"
  significance: string;
}

export interface FestivalsResult {
  festivals: FestivalItem[];
}

/* ── Turant Uttar AI narration (/v1/ai/turant-uttar) ────────────────────── */

export interface TurantUttarAIResult {
  opening: string;
  /** How Vedic astrology judges this topic in general — the educational lens. */
  topic_insight: string;
  /** The main reading — 10+ lines when Haiku-narrated. */
  narrative: string;
  timing_note: string;
  remedies: string[];
  /** Practical behaviour/timing suggestions, not rituals. */
  tips: string[];
  dossier: Record<string, unknown>;
  narrated_by: "haiku" | "template";
  powered_by: string;
}

/* ── Mangal Dosha (/v1/milan/mangal-dosha) ──────────────────────────────── */

export interface MangalDoshaPerson {
  has_mangal_dosha: boolean;
  manglik_from_lagna: boolean;
  manglik_from_moon: boolean;
  mars_house: number;
  mars_house_from_moon: number;
  cancellations: string[];
  severity: string;      // none | low | high...
  mars_sign: string;
  mars_sign_hi: string;
  mars_dms?: string;
  mars_retrograde?: boolean;
}

export interface MangalDoshaResult {
  person1: MangalDoshaPerson;
  person2: MangalDoshaPerson;
  mutual_cancellation: boolean;
  note: string;
}

/* ── Sade Sati (/v1/transits/sade-sati) ─────────────────────────────────── */

export interface SadeSatiWindow {
  start: string;
  end: string;
}

export interface SadeSatiPhase {
  phase: string;        // rising | peak | setting
  phase_hi: string;
  sign: string;
  from: string;
  to: string;
}

export interface SadeSatiResult {
  natal_moon_sign: string;
  natal_moon_sign_hi: string;
  saturn_current_sign: string;
  saturn_current_sign_hi: string;
  saturn_longitude: number;
  saturn_degree_in_sign: number;
  saturn_retrograde: boolean;
  in_sade_sati: boolean;
  current_phase: string | null;
  current_phase_hi: string | null;
  sade_sati_signs: string[];
  current_sade_sati: SadeSatiWindow | null;
  current_phases: SadeSatiPhase[] | null;
  previous_sade_sati: SadeSatiWindow | null;
  next_sade_sati: SadeSatiWindow | null;
  in_dhaiya: boolean;
  dhaiya_type: string | null;
  dhaiya_hi: string | null;
  remedies: string[];
  note: string;
}
