/**
 * GrahaAPI types — generated by hand FROM REAL LIVE RESPONSES
 * (https://api.grahaapi.com, verified 2026-07-19 against /openapi.json and
 * live POSTs to all five wired endpoints). Do not "guess" fields here:
 * every field below was observed in an actual response or the OpenAPI spec.
 */

/* ── Requests (from /openapi.json component schemas) ────────────────────── */

export interface BirthRequest {
  dob: string;          // YYYY-MM-DD
  tob?: string;         // HH:MM — omit for sunrise chart
  lat: number;
  lon: number;
  tz: number;           // IST = 5.5
  name?: string;
  gender?: "male" | "female";
}

/** /v1/milan/ashtakoot — the live schema really is person1/person2. */
export interface MilanRequest {
  person1: BirthRequest;
  person2: BirthRequest;
}

export interface TarotRequest {
  question?: string;
  spread?: "single" | "three_card" | "celtic_cross" | "yes_no" | "past_present_future";
  deck?: "rider_waite" | "thoth" | "osho_zen" | "marseille";
  birth_chart?: BirthRequest;
  seed?: number;
}

/** /v1/rashifal/daily — POST only; takes NO rashi (returns all 12). */
export interface RashifalRequest {
  date?: string;        // YYYY-MM-DD, default today
  tz?: number;
}

export interface TransitBirthRequest {
  birth: BirthRequest;
  transit_date: string; // YYYY-MM-DD
  transit_time?: string;
}

/* ── Kundli (/v1/kundli/full) ───────────────────────────────────────────── */

export interface Nakshatra {
  index: number;
  name: string;
  name_hi: string;
  lord: string;
  pada: number;
  progress: number;
}

export interface Planet {
  longitude: number;
  latitude: number;
  distance: number;
  speed: number;
  retrograde: boolean;
  sign_index: number;
  sign: string;
  sign_hi: string;
  degrees: number;
  dms: string;
  house: number;
  dignity: string;
  interpretation_sign?: string;
  interpretation_house?: string;
  nakshatra?: Nakshatra;
  navamsa?: { sign_index: number; sign: string; sign_hi: string; navamsa_num: number };
  is_exalted?: boolean;
  is_debilitated?: boolean;
  is_mool_trikona?: boolean;
  is_own_sign?: boolean;
  is_combust?: boolean;
  is_vargottama?: boolean;
  avastha?: string;
}

export interface Yoga {
  name: string;
  name_hi?: string;
  planets: string[];
  strength: string;
  description_hi?: string;
  description: string;
}

/** One vimshottari level: { lord, start, end } — NOT a flat string. */
export interface DashaPeriod {
  lord: string;
  start: string;
  end: string;
}

export interface CurrentDasha {
  mahadasha: DashaPeriod;
  antardasha?: DashaPeriod;
  pratyantar?: DashaPeriod;
  sookshma?: DashaPeriod;
  prana?: DashaPeriod;
}

/** /v1/dasha/mahadasha — full 9-period Vimshottari sequence (~120 years). */
export interface MahadashaListResult {
  dasha: {
    moon_nakshatra: string;
    moon_nakshatra_hi: string;
    nakshatra_lord: string;
    nakshatra_progress: number;
    current: CurrentDasha;
    mahadasha: Array<{ lord: string; start: string; end: string; years?: number }>;
  };
}

export interface KundliFullResult {
  ascendant: {
    tropical: number;
    sidereal: number;
    ayanamsa: number;
    sign_index: number;
    sign: string;
    sign_hi: string;
    degrees: number;
    dms: string;
  };
  /** Array, not a Record — [{house, sign_index, sign, sign_hi, start, end}] */
  houses: Array<{
    house: number;
    sign_index: number;
    sign: string;
    sign_hi: string;
    start: number;
    end: number;
  }>;
  planets: Record<string, Planet>;
  moon_nakshatra: Nakshatra;
  yogas: Yoga[];
  current_dasha: CurrentDasha;
  lagna_personality: string;
}

/* ── Milan (/v1/milan/ashtakoot) ────────────────────────────────────────── */

export interface AshtakootResult {
  varna: { score: number; max: number; boy_varna: string; girl_varna: string };
  vashya: { score: number; max: number; boy_group: string; girl_group: string };
  tara: { score: number; max: number; tara_from_boy?: number; tara_from_girl?: number; auspicious?: boolean };
  yoni: { score: number; max: number; boy_yoni: string; girl_yoni: string };
  graha_maitri: {
    score: number; max: number;
    boy_moon_sign_lord?: string; girl_moon_sign_lord?: string;
  };
  gana: { score: number; max: number; boy_gana: string; girl_gana: string };
  bhakoot: { score: number; max: number; difference?: number; note?: string };
  nadi: { score: number; max: number; boy_nadi?: string; girl_nadi?: string; nadi_dosha: boolean };
  total: number;        // can be fractional (e.g. 20.0, tara gives halves)
  max: number;          // 36
  percentage: number;
  verdict: string;      // bilingual, e.g. "सामान्य / Average"
  person1?: {
    nakshatra: string; nakshatra_lord: string;
    moon_sign: string; moon_sign_hi: string; moon_dms?: string;
  };
  person2?: {
    nakshatra: string; nakshatra_lord: string;
    moon_sign: string; moon_sign_hi: string; moon_dms?: string;
  };
}

/* ── Rashifal (/v1/rashifal/daily) — ALL 12 rashis in one response ──────── */

export interface RashiPredictionTexts {
  overall: string;
  career: string;
  health: string;
  finance: string;
  love: string;
  spirit: string;
  stars_label: string;
}

export interface RashiPrediction {
  rashi_index: number;
  rashi_en: string;
  rashi_hi: string;
  rashi_lord: string;
  symbol: string;
  overall_stars: number;                 // 1–5
  domain_stars: { career: number; health: number; finance: number; love: number; spirit: number };
  lucky: { number: number; colors: string[]; day: string; mantra: string };
  auspicious_hours: string[];            // e.g. "06:00-07:30"
  predictions_hi: RashiPredictionTexts;
  predictions_en: RashiPredictionTexts;
}

export interface RashifalDailyResult {
  date: string;
  rashifal: RashiPrediction[];           // always 12 entries
  transit_summary: Record<
    string,
    { sign: string; sign_hi: string; sign_index: number; longitude: number; retrograde: boolean }
  >;
}

/* ── Tarot (/v1/tarot/draw) ─────────────────────────────────────────────── */

export interface TarotCard {
  id: number;
  name: string;
  name_hi: string;
  suit: string;
  value: string;
  element: string;                       // e.g. "Air / वायु"
  domain: string;
  keywords: string[];
  position: string;                      // "card_1"…
  reversed: boolean;
  interpretation_hi: string;
  interpretation_en: string;
}

export interface TarotResult {
  reading: { reading_id: string; timestamp: string; seed_used: number | null; seed_str: string };
  spread: string;
  deck: string;
  cards_drawn: number;
  cards: TarotCard[];
  question: string | null;
  note: string;
}

/* ── Panchang (/v1/panchang/full, /v1/panchang/rahu-kaal, /v1/panchang/muhurta) ── */

export interface PanchangFullResult {
  date: string;
  tithi: { number: number; paksha: string; name: string; name_hi?: string; paksha_num: number; completion: number; end_time: string };
  nakshatra: { index: number; name: string; name_hi: string; lord: string; pada: number; progress: number; end_time: string };
  yoga: { index: number; name: string; progress: number; end_time: string };
  karana: { number: number; name: string; completion: number; end_time: string };
  vara: { index: number; name: string; lord: string; note?: string };
  /** Purnimanta (North Indian) lunar month; masa_amanta = Amanta name. */
  masa?: { index: number; name: string; name_hi: string };
  masa_amanta?: { index: number; name: string; name_hi: string };
  moon_phase: string;
  sun_rise: string;
  sun_set: string;
}

export interface KaalWindow {
  start: string;
  end: string;
  note: string;
}

export interface RahuKaalResult {
  vara: string;
  rahu_kaal: KaalWindow;
  gulika_kaal: KaalWindow;
  yamaganda: KaalWindow;
  sunrise: string;
  sunset: string;
}

export interface MuhurtaSlot {
  slot: number;
  name: string;
  type: string;          // day | night
  start: string;
  end: string;
  quality: string;       // Auspicious | Inauspicious | ...
  abhijit?: boolean;
}

export interface MuhurtaResult {
  muhurta: MuhurtaSlot[];
}

export interface FestivalItem {
  date: string;          // YYYY-MM-DD
  name: string;          // "Raksha Bandhan" / "Shukla Ekadashi (एकादशी)"
  name_hi?: string;      // "रक्षाबंधन"
  significance: string;
  /** True for named major festivals (Diwali, Holi, Teej, Navratri, Makar
   *  Sankranti …) as opposed to routine tithi vrats. */
  major?: boolean;
}

export interface MasaInfo {
  index: number;
  name: string;     // e.g. "Shravana"
  name_hi: string;  // e.g. "श्रावण"
}

/** Per-day tithi + lunar month, for labeling every calendar cell.
 *  masa/masa_hi are Purnimanta (North Indian standard — months end at
 *  Purnima); masa_amanta* carry the Amanta (South/West) name. */
export interface PanchangDayInfo {
  date: string;      // YYYY-MM-DD
  tithi: string;     // "Krishna Tritiya" / "Purnima"
  tithi_hi: string;  // "कृष्ण तृतीया" / "पूर्णिमा"
  masa: string;      // "Shravana" (Purnimanta)
  masa_hi: string;   // "श्रावण"
  masa_amanta?: string;
  masa_amanta_hi?: string;
}

export interface FestivalsResult {
  festivals: FestivalItem[];
  days?: PanchangDayInfo[];
  masa_start?: MasaInfo;
  masa_end?: MasaInfo;
}

/* ── Turant Uttar AI narration (/v1/ai/turant-uttar) ────────────────────── */

export interface TurantUttarAIResult {
  opening: string;
  /** How Vedic astrology judges this topic in general — the educational lens. */
  topic_insight: string;
  /** The main reading — 10+ lines when Haiku-narrated. */
  narrative: string;
  timing_note: string;
  remedies: string[];
  /** Practical behaviour/timing suggestions, not rituals. */
  tips: string[];
  dossier: Record<string, unknown>;
  narrated_by: "haiku" | "template";
  powered_by: string;
}

/* ── Mangal Dosha (/v1/milan/mangal-dosha) ──────────────────────────────── */

export interface MangalDoshaPerson {
  has_mangal_dosha: boolean;
  manglik_from_lagna: boolean;
  manglik_from_moon: boolean;
  mars_house: number;
  mars_house_from_moon: number;
  cancellations: string[];
  severity: string;      // none | low | high...
  mars_sign: string;
  mars_sign_hi: string;
  mars_dms?: string;
  mars_retrograde?: boolean;
}

export interface MangalDoshaResult {
  person1: MangalDoshaPerson;
  person2: MangalDoshaPerson;
  mutual_cancellation: boolean;
  note: string;
}

/* ── Sade Sati (/v1/transits/sade-sati) ─────────────────────────────────── */

export interface SadeSatiWindow {
  start: string;
  end: string;
}

export interface SadeSatiPhase {
  phase: string;        // rising | peak | setting
  phase_hi: string;
  sign: string;
  from: string;
  to: string;
}

export interface SadeSatiResult {
  natal_moon_sign: string;
  natal_moon_sign_hi: string;
  saturn_current_sign: string;
  saturn_current_sign_hi: string;
  saturn_longitude: number;
  saturn_degree_in_sign: number;
  saturn_retrograde: boolean;
  in_sade_sati: boolean;
  current_phase: string | null;
  current_phase_hi: string | null;
  sade_sati_signs: string[];
  current_sade_sati: SadeSatiWindow | null;
  current_phases: SadeSatiPhase[] | null;
  previous_sade_sati: SadeSatiWindow | null;
  next_sade_sati: SadeSatiWindow | null;
  in_dhaiya: boolean;
  dhaiya_type: string | null;
  dhaiya_hi: string | null;
  /** Combined bilingual strings (legacy); prefer remedies_hi/remedies_en. */
  remedies: string[];
  remedies_hi?: string[];
  remedies_en?: string[];
  note: string;
  note_hi?: string;
  note_en?: string;
}

/* ── Rectification (/v1/rectification/* — sourced directly from
   backend/app/routers/rectification.py, added this session, not a captured
   live response — kept accurate to the actual return dicts in that file) ── */

export interface AscendantOptionsRequest {
  dob: string;   // YYYY-MM-DD
  lat: number;
  lon: number;
  tz: number;
}

export interface AscendantWindow {
  sign: string;
  sign_hi: string;
  start_local: string;   // HH:MM
  end_local: string;     // HH:MM
  ruling_planet: string;
  element: string;
  quality: string;
  body_features: string[];
  personality: string[];
  career_indicators: string[];
  health_areas: string[];
  hi: string;
}

export interface AscendantOptionsResult {
  dob: string;
  lat: number; lon: number; tz: number;
  total_ascendants: number;
  ascendant_windows: AscendantWindow[];
  note_en: string;
  note_hi: string;
}

export type RectEventType =
  | "marriage" | "divorce" | "child_birth" | "job_start" | "job_loss" | "promotion"
  | "accident" | "illness" | "surgery" | "death_relative" | "foreign_travel"
  | "property" | "education" | "business" | "spiritual" | "financial_gain"
  | "financial_loss" | "relocation" | "legal_trouble" | "award";

export interface RectEvent {
  date: string;   // YYYY-MM-DD
  type: RectEventType;
  note?: string;
}

export interface RectCandidate {
  date: string;      // YYYY-MM-DD — the day this candidate tests (equals dob when day_unknown=false)
  tob: string;        // HH:MM
  ascendant: string;
  ascendant_hi: string;
  ascendant_lord: string;
  moon_nakshatra: string;
  house_lords: Record<string, string>;
  score: number;
  confidence_pct: number;
  event_breakdown: Array<{ date: string; type: RectEventType; score: number; relevant_houses: number[] }>;
}

export interface EventScoreResult {
  dob: string;
  day_unknown: boolean;
  days_scanned: number;
  approx_tob: string;
  search_range: string;
  step_minutes: number;
  events_used: number;
  candidates_tested: number;
  top_candidates: RectCandidate[];
  best_match: RectCandidate | null;
  disclaimer_en: string;
  disclaimer_hi: string;
}

export interface KpRulingWindow {
  tob: string;
  lagna_sign: string;
  lagna_sign_lord: string;
  lagna_nak_lord: string;
  lagna_sub_lord: string;
  matches_ruling_planets: boolean;
}

export interface KpRulingResult {
  dob: string;
  approx_tob: string;
  query_moment: string;
  ruling_planets: string[];
  ruling_planet_detail: Record<string, string>;
  candidate_windows: KpRulingWindow[];
  matched_windows: KpRulingWindow[];
  note_en: string;
  note_hi: string;
}

/* ── Lal Kitab (/v1/lalkitab/full) ───────────────────────────────────────── */

export interface LalKitabLagna {
  sign: string;
  sign_hi: string;
  sign_index: number;
  sidereal: number;
}

export interface LalKitabPlanetEntry {
  house: number;
  sign: string;
  sign_hi: string;
  sign_index: number;
  longitude: number;
  degree_in_sign: number;
  dms: string;
  retrograde: boolean;
  speed: number;
  pakka_ghar: number[];
  in_pakka_ghar: boolean;
}

export interface LalKitabDebt {
  name: string;
  name_hi: string;
  indicator: string;
  remedy: string;
  active: boolean;
}

export interface LalKitabPrediction {
  planet: string;
  house: number;
  sign: string;
  in_pakka_ghar: boolean;
  prediction: string;
}

export interface LalKitabUpaya {
  planet: string;
  house: number | null;
  reason: string;
  upayas: string[];
}

export interface LalKitabPakkaGharEntry {
  pakka_ghar: number[];
  placed_in_house: number;
  in_pakka_ghar: boolean;
  sign: string;
}

export interface LalKitabFullResult {
  lagna: LalKitabLagna;
  chart: Record<string, LalKitabPlanetEntry>;
  debts: LalKitabDebt[];
  predictions: LalKitabPrediction[];
  upayas: LalKitabUpaya[];
  pakka_ghar: Record<string, LalKitabPakkaGharEntry>;
}

/* ── Lucky Colors (/v1/remedies/colors) — no Hindi fields on this endpoint ── */

export interface LuckyColorsResult {
  lagna: string;
  lagna_lord: string;
  nakshatra_lord: string;
  auspicious_colors: string[];
  inauspicious_colors: string[];
  note: string;
}

/* ── Special Yogas / Kaal Sarpa (/v1/rajyog/special-yogas) ──────────────── */

export interface SpecialYoga {
  name: string;
  name_hi: string;
  type: string;
  planets: string[];
  strength: string;
  effect_en: string;
  effect_hi: string;
  /** Only present on "Kaal Sarpa Yoga". */
  direction?: "Udit Golardha (Rahu→Ketu)" | "Anudit Golardha (Ketu→Rahu)";
}

export interface SpecialYogasResult {
  special_yogas: SpecialYoga[];
  count: number;
}

/* ── Shared numerology request bodies (/v1/numerology/*) ───────────────── */

export interface DobRequest {
  dob: string;
  name?: string;
  system?: "chaldean" | "pythagorean";
}

export interface NumerologyRequest {
  /** Key must be present (may be ""); Personal Year's handler never reads it. */
  name: string;
  dob: string;
  system?: "chaldean" | "pythagorean";
}

/* ── Favorable Alphabet / Cornerstone (/v1/numerology/first-letter) ─────── */

export interface CornerstoneLetter {
  letter: string;
  value: number;
  meaning_en: string;
  meaning_hi: string;
  ruling_planet: string;
  ruling_planet_hi: string;
  gemstone: string;
  gemstone_hi: string;
  colour: string;
}

/** No _hi fields on ruling_planet/gemstone — asymmetric with CornerstoneLetter by API design. */
export interface CapstoneLetter {
  letter: string;
  value: number;
  meaning_en: string;
  meaning_hi: string;
  ruling_planet: string;
  gemstone: string;
  colour: string;
}

export interface FirstLetterResult {
  name: string;
  first_letter: string;
  last_letter: string;
  cornerstone: CornerstoneLetter;
  capstone: CapstoneLetter;
  career_resonance: string;
  recommended_careers: string[];
  interpretation_en: string;
  interpretation_hi: string;
}

/* ── Personal Year (/v1/numerology/personal-year) ───────────────────────── */

export interface PersonalYearAdjacent {
  year: number;
  number: number;
  theme: string;
}

export interface PersonalYearMeaning {
  title: string;
  hi: string;
  en: string;
  strengths: string[];
  challenges: string[];
  lucky_color: string;
  ruling_planet: string;
}

export interface PersonalYearResult {
  current_year: number;
  personal_year: number;
  theme: string;
  meaning: PersonalYearMeaning;
  ruling_planet: string;
  ruling_planet_hi: string;
  gemstone: string;
  gemstone_hi: string;
  colour: string;
  colour_hi: string;
  mantra: string;
  mantra_devanagari: string;
  favourable_days: string[];
  previous_year: PersonalYearAdjacent;
  next_year: PersonalYearAdjacent;
  advice_en: string;
  advice_hi: string;
  interpretation_en: string;
  interpretation_hi: string;
}

/* ── Karmic Debt (/v1/numerology/karmic-debt) ────────────────────────────── */

export type KarmicDebtPosition = "birth_day" | "bhagyank_pre_reduction" | "name_number";

export interface KarmicDebtFound {
  position: KarmicDebtPosition;
  number: number;
  info: { en: string; hi: string };
}

export interface KarmicDebtResult {
  dob: string;
  name: string | null;
  karmic_debts_found: KarmicDebtFound[];
  has_karmic_debt: boolean;
  interpretation_en: string;
  interpretation_hi: string;
}

/* ── Missing/Repeated Numbers (/v1/numerology/missing-numbers) ──────────── */

export interface MissingLesson {
  en: string;
  hi: string;
  ruling_planet: string;
  ruling_planet_hi: string;
  gemstone: string;
  gemstone_hi: string;
  colour: string;
  remedy_en: string;
  remedy_hi: string;
}

/** NOT the same shape as MissingLesson — fewer fields, no _hi/colour/remedy. */
export interface RepeatedStrength {
  en: string;
  hi: string;
  ruling_planet: string;
  gemstone: string;
}

export interface MissingNumbersResult {
  dob: string;
  missing_numbers: number[];
  repeated_numbers: number[];
  missing_lessons: Record<string, MissingLesson>;
  repeated_strengths: Record<string, RepeatedStrength>;
  interpretation_en: string;
  interpretation_hi: string;
}

/* ── Weekly Rashifal (/v1/rashifal/weekly) ───────────────────────────────── */

/** rashi is the ENGLISH rashi name (e.g. "Scorpio"), not an index. */
export interface BySignRequest {
  rashi: string;
  date?: string;
  tz?: number;
}

export interface WeeklyRashifalDay {
  date: string;
  weekday: string;
  overall_stars: number;
  domain_stars: { career: number; health: number; finance: number; love: number; spirit: number };
  overall_hi: string;
  overall_en: string;
  lucky_number: number;
  auspicious_hours: string[];
  saturn_influence: string | null;
}

export interface WeeklyRashifalResult {
  rashi_en: string;
  rashi_hi: string;
  week_start: string;
  week_end: string;
  week_average_stars: number;
  best_day: string | null;
  summary_hi: string;
  summary_en: string;
  days: WeeklyRashifalDay[];
}

/* ── Numerology Compatibility Suite (premium, /v1/site/numerology-suite) ── */

export interface LoveBlock {
  mulank_love: Record<string, unknown> & { number: number };
  bhagyank_love: Record<string, unknown> & { number: number };
  compatible_numbers: number[];
  incompatible_numbers: number[];
  interpretation_en: string;
  interpretation_hi: string;
}

export interface CareerBlock {
  mulank_careers: Record<string, unknown> & { number: number };
  bhagyank_careers: Record<string, unknown> & { number: number };
  combo_theme: Record<string, unknown>;
  strongest_careers: string[] | null;
  interpretation_en: string;
  interpretation_hi: string;
}

export interface BusinessBlock {
  best_business_partners: number[];
  good_business_partners: number[];
  challenging_partners: number[];
  compatibility_scores: Record<string, number>;
  interpretation_en: string;
  interpretation_hi: string;
}

export interface MarriageBlock {
  mulank_marriage: Record<string, unknown> & { number: number };
  bhagyank_marriage: Record<string, unknown> & { number: number };
  soul_urge_marriage: (Record<string, unknown> & { number: number }) | null;
  compatible_partner_numbers: number[];
  favourable_years_for_marriage: number[];
  interpretation_en: string;
  interpretation_hi: string;
}

export interface NumerologySuiteResult {
  dob: string;
  name: string | null;
  mulank: number;
  bhagyank: number;
  love: LoveBlock;
  career: CareerBlock;
  business: BusinessBlock;
  marriage: MarriageBlock;
  narrative_en: string;
  narrative_hi: string;
}

/* ── Yearly Horoscope / Varshphal (premium, /v1/site/varshphal-yearly) ──── */

export interface VarshphalPredictions {
  career: string;
  finance: string;
  health: string;
  relationships: string;
  spiritual: string;
  year_lord_influence: string;
}

export interface VarshphalYearlyResult {
  year: number;
  predictions: VarshphalPredictions;
  overall_year_score: number;
  varshesha: string;
  varshesha_role: string;
  muntha_house: number;
  note: string;
}

/* ── Varshphal free teaser endpoints (/v1/varshphal/year-lord, /muntha) ──── */

export interface VarshphalYearLordResult {
  year: number;
  solar_return_date: string;
  varshesha: string;
  varshesha_role: string;
  varshesha_quality: string;
  varshesha_sign: string;
  varshesha_sign_hi: string;
  varshesha_house: number;
  note: string;
}

export interface VarshphalMunthaResult {
  year: number;
  muntha_sign: string;
  muntha_sign_hi: string;
  muntha_house_from_varsha_lagna: number;
  muntha_lord: string;
  muntha_lord_sign: string;
  effect: string;
  note: string;
}
